import { createElement } from 'lwc';
import EstateXpert_Control_Center from 'c/estateXpert_Control_Center';

describe('c-estate-xpert-control-center', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-estate-xpert-control-center', {
            is: EstateXpert_Control_Center
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});